server:
  port: "8080"
  host: "0.0.0.0"

btcpay:
  base_url: "https://your-btcpay-server.com"
  api_key: ""  # To be provided via environment variable
  store_id: "" # To be provided via environment variable

mongodb:
  uri: "mongodb://localhost:27017"
  database: "btcpay_integration"
  collection: "transactions"